[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#db0011"
backgroundColor="#f0f0f0"
secondaryBackgroundColor="#ffffff"
textColor="#000000"
font="sans serif"
